services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: paysera_php
    volumes:
      - ../:/srv/www
    environment:
      APP_ENV: dev
      APP_SECRET: change-this-secret-key-in-production-min-32-chars
      DATABASE_URL: "mysql://paysera_user:paysera_pass_2025@mysql:3306/paysera_db"
      REDIS_URL: "redis://redis:6379"
      APP_API_TOKENS: '["token1","token2"]'
    depends_on:
      - mysql
      - redis
    networks:
      - paysera_net

  nginx:
    image: nginx:1.25
    container_name: paysera_nginx
    ports:
      - "8080:80"
    volumes:
      - ../:/srv/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - paysera_net

  mysql:
    image: mysql:8.0
    container_name: paysera_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paysera_db
      MYSQL_USER: paysera_user
      MYSQL_PASSWORD: paysera_pass_2025
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - paysera_net

  redis:
    image: redis:7-alpine
    container_name: paysera_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - paysera_net

  composer:
    image: composer:2
    container_name: paysera_composer
    working_dir: /srv/www
    volumes:
      - ../:/srv/www
    depends_on:
      - php

networks:
  paysera_net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
